# 使用官方 Python 映像
FROM python:3.10-slim

# 設定工作目錄
WORKDIR /app

# 複製當前目錄的檔案到容器中的工作目錄
COPY . .

# 安裝所需套件
RUN pip install --upgrade pip \
    && pip install -r requirements.txt

# 暴露 Django 預設的埠
EXPOSE 8000

# 執行 Django 伺服器
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]