# Generated by Django 4.2.16 on 2024-11-18 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_stocks', models.CharField(blank=True, max_length=1000, null=True)),
                ('selected_stocks2', models.CharField(blank=True, max_length=1000, null=True)),
                ('start_date', models.CharField(blank=True, max_length=1000, null=True)),
                ('end_date', models.CharField(blank=True, max_length=1000, null=True)),
                ('window_size', models.CharField(blank=True, max_length=1000, null=True)),
                ('fintech_data', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
