# Generated by Django 5.1.1 on 2024-10-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_tool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='stock_date_start',
        ),
        migrations.AddField(
            model_name='profile',
            name='end_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='selected_stocks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='selected_stocks2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='start_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='window_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
